import os
import sys
import json
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def upload_video(video_file="output_video.mp4", title="News Video", description="Generated by AI Video Pipeline"):
    # 1. Pobranie danych uwierzytelniających z sekretu GitHub Actions
    creds_json = os.environ.get("YOUTUBE_CREDENTIALS")
    if not creds_json:
        print("Error: YOUTUBE_CREDENTIALS secret is not set.")
        sys.exit(1)

    if not os.path.exists(video_file):
        print(f"Error: File {video_file} not found.")
        sys.exit(1)

    # 2. Odczytanie i przygotowanie poświadczeń OAuth2
    try:
        creds_data = json.loads(creds_json)
        credentials = Credentials.from_authorized_user_info(creds_data)
    except Exception as e:
        print(f"Error parsing YOUTUBE_CREDENTIALS: {e}")
        sys.exit(1)

    # 3. Połączenie z YouTube API
    youtube = build("youtube", "v3", credentials=credentials)

    # 4. Metadane filmu
    body = {
        "snippet": {
            "title": title[:100],  # YouTube ogranicza tytuł do 100 znaków
            "description": description,
            "categoryId": "25"     # Kategoria: News & Politics
        },
        "status": {
            "privacyStatus": "public"  # Opcje: public, unlisted, private
        }
    }

    # 5. Wszywanie pliku wideo
    media = MediaFileUpload(video_file, chunksize=-1, resumable=True, mimetype="video/mp4")
    
    print(f"Uploading {video_file} to YouTube...")
    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Uploaded {int(status.progress() * 100)}%")

    print(f"Upload complete! Video ID: {response.get('id')}")

if __name__ == "__main__":
    # Pobranie tytułu i opisu ze zmiennych środowiskowych przekazanych przez workflow
    video_title = os.environ.get("VIDEO_TITLE", "AI News Update")
    video_description = os.environ.get("SCRIPT_TEXT", "Automated news update.")
    
    upload_video(
        video_file="output_video.mp4",
        title=video_title,
        description=video_description
    )
